services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: RMS
    environment:
      SA_PASSWORD: "Password@2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql 
    networks:
      - app-network

  recruitment-backend:
    build: ./backend
    container_name: recruitment-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=RMS;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Password@2025
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      - sqlserver
    networks:
      - app-network
    restart: on-failure

  recruitment-frontend:
    build: ./frontend/recruitment-frontend 
    container_name: recruitment-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://recruitment-backend:8080/api
    depends_on:
      - recruitment-backend
    networks:
      - app-network

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge